pipeline {
    agent any
    stages {
        stage("clone"){
            steps{
                sh "git clone https://github.com/iamKrishnendu/selenium-docker.git"
            }
        }
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'mvn clean install -Dbrowser=chrome'
            }
        }
    }

post{
     always{
        echo "Build ${currentBuild.fullDisplayName} has ${currentBuild.currentResult}."
        cleanWs()
        }
    }
}