pipeline {
    agent any
    stages {
        stage("clone"){
            steps{
                sh "git clone https://github.com/iamKrishnendu/selenium-docker.git"
            }
        }
        stage("build-docker-compose"){
            steps{
                sh 'cd ./docker'
                sh 'docker-compose up -d'
            }
        }
        stage('build') {
            steps {
                sh 'mvn --version'
                sh 'mvn clean install -Dbrowser=chrome'
            }
        }
    }

post{
     always{
        cleanWs()
        }
    }
}